name: Host Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Download and install ngrok
        run: |
          curl -s https://bin.equinox.io/c/4b397n7Adw7/ngrok-stable-linux-amd64.tgz -o ngrok.tgz
          tar xzf ngrok.tgz
          sudo mv ngrok /usr/local/bin/

      - name: Run application
        run: |
          npm start &
          sleep 10  # wait for the application to start

      - name: Expose application with ngrok
        run: |
          ngrok http 3000 > /dev/null &
          sleep 10  # wait for ngrok to establish the tunnel

      - name: Get ngrok URL
        run: |
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      - name: Run tests
        run: npm test
